# Generated by Django 4.2.1 on 2023-08-14 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='album_img', verbose_name='이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.CharField(max_length=24, verbose_name='모임명')),
                ('info', models.CharField(blank=True, max_length=128, null=True, verbose_name='모임소개글')),
                ('code', models.UUIDField(primary_key=True, serialize=False, unique=True, verbose_name='모임초대코드')),
                ('profile', models.ImageField(null=True, upload_to='group_profile', verbose_name='모임이미지')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts_img', verbose_name='이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('group_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.group')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(blank=True, null=True, upload_to='user_profile', verbose_name='프로필이미지')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=15, region=None, verbose_name='전화번호')),
                ('like_posts', models.ManyToManyField(related_name='liked_users', to='posts.post')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=8, null=True)),
                ('date', models.CharField(max_length=8, null=True)),
                ('title', models.TextField(null=True)),
                ('memo', models.CharField(max_length=24, null=True)),
                ('group_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='posts.group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.ManyToManyField(to='posts.userinfo'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
