# Generated by Django 4.2.4 on 2023-08-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_phonenumber_userinfo_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='모임명')),
                ('info', models.CharField(blank=True, max_length=128, null=True, verbose_name='모임소개글')),
                ('code', models.UUIDField(verbose_name='모임초대코드')),
            ],
        ),
    ]
