# Generated by Django 4.2.4 on 2023-08-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='profile',
            field=models.ImageField(null=True, upload_to='group_profile', verbose_name='모임이미지'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile', verbose_name='프로필이미지'),
        ),
    ]
