# Generated by Django 4.2.4 on 2023-08-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_group_profile_alter_userinfo_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='id',
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=24, primary_key=True, serialize=False, verbose_name='모임명'),
        ),
    ]
