# Generated by Django 4.2.4 on 2023-08-10 06:39

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_group_code_alter_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=15, region=None, unique=True, verbose_name='전화번호'),
        ),
    ]
