# Generated by Django 4.2.4 on 2023-08-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_userinfo_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='group',
            field=models.ManyToManyField(null=True, to='posts.group', verbose_name='사용자 그룹'),
        ),
    ]
