# Generated by Django 4.2.4 on 2023-08-10 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_group_post_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='group',
        ),
    ]
