# Generated by Django 4.2.4 on 2023-08-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_album_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='test',
            field=models.TextField(default='없음', verbose_name='확인'),
        ),
    ]
