# Generated by Django 4.2.4 on 2023-08-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_album_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='title',
            field=models.TextField(default='기본값', verbose_name='테스트용'),
        ),
    ]
