# Generated by Django 4.2.4 on 2023-08-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_rename_author_comment_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.ManyToManyField(to='posts.userinfo'),
        ),
    ]
