# Generated by Django 4.2.4 on 2023-08-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_alter_userinfo_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='like_posts',
            field=models.ManyToManyField(to='posts.post'),
        ),
    ]
