# Generated by Django 4.2.4 on 2023-08-12 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_alter_group_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=8)),
                ('date', models.CharField(max_length=8)),
                ('title', models.TextField()),
                ('memo', models.CharField(max_length=24, null=True)),
                ('group_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='posts.group')),
            ],
        ),
    ]
