# Generated by Django 4.2.4 on 2023-08-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='date',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='month',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
