# Generated by Django 4.2.4 on 2023-08-10 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_album_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='test',
        ),
        migrations.RemoveField(
            model_name='album',
            name='writer',
        ),
    ]
