# Generated by Django 4.2.4 on 2023-08-10 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_post_group'),
        ('posts', '0016_rename_title_album_test'),
    ]

    operations = [
    ]
