# Generated by Django 4.2.4 on 2023-08-12 09:11

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_group_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=15, region=None, verbose_name='전화번호'),
        ),
    ]
