# Generated by Django 4.2.1 on 2023-08-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_alter_plan_date_alter_plan_month_alter_plan_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='like_posts',
            field=models.ManyToManyField(related_name='liked_users', to='posts.post'),
        ),
    ]
